# Nathanael Gandhi https://github.com/NathanaelGandhi/
# MPL-2.0 licence

name: 'Label stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
    
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  call-reusable:
    uses: NathanaelGandhi/reusable-workflows/.github/workflows/stale-reusable.yaml@0.1.5
    secrets: inherit

